# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d20fdb0f3d7ba7f9ff6c48b869bbaf565403dff9e497b3dee2dd81c21026ab27d262ca000c3bffd75480e8789bae58b5081cb00b7d69fa5ca7ff3e7ec95230f6

test:
  secret_key_base: a41c06c1f651dee8297944e5b92044e8511c167f7ed82e72b441433303633e9128c03ff8e9d0ba821240f2c7e8d19f9f9ffb85b80b303d93b35a4dd3be978c4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
